[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
anchor_counter = "4bQnJG1f7Vcp5bDRqRmJmUB92MJ39FvCtWfHx5QLXfqn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/phamtu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
